### PR TITLE
Add Modal complexity factor

### PR DESCRIPTION
**Pull request by nilswagner**

### CODE REVIEW

**Comment by jankoslavic** [comment]
Thanks @nilswagner Looks good to me. @klemengit , @domengorjup ?

**Review by domengorjup — COMMENTED** [review]
The code looks good to me. The documentation could be expanded a bit, to clearly define the input and output parameters (something along the lines of what's done in [`MSF`](https://github.com/ladisk/pyEMA/blob/fe1e799e3b2c09e4891c5695d2f2bd53bc4d7feb/pyEMA/tools.py#L63)).

**Comment by jankoslavic** [comment]
Additional source would be also beneficial; eg: http://www.svibs.com/resources/ARTeMIS_Modal_Help/Generic%20Complexity%20Plot.html @nilswagner will you be able to add this commit?

**Comment by klemengit** [comment]
I agree with the comments. Also, it would be a good idea to add a test. Existing test data in ``pyEMA/test_data.py`` can be used.

**Review by klemengit — APPROVED** [review]
I added the docstring and a basic test. With this I'm also closing issue #25

**Pull request merged**
